# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CSNetworking' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CSNetworking
  pod 'AFNetworking', '~> 3.1.0'

  target 'CSNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
